In [5]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv('nba_games.csv')
data.head()

,Date,Full Name (Data.Home Team),Full Name (Data.Visitor Team),Home Team Score,Visitor Team Score
0,2020-12-22T00:00:00.000Z,Brooklyn Nets,Golden State Warriors,125,99
1,2020-12-22T00:00:00.000Z,Los Angeles Lakers,LA Clippers,109,116
2,2020-12-25T00:00:00.000Z,Miami Heat,New Orleans Pelicans,111,98
3,2020-12-26T00:00:00.000Z,Washington Wizards,Orlando Magic,120,130
4,2020-12-23T00:00:00.000Z,Cleveland Cavaliers,Charlotte Hornets,121,114

In [7]:
nba2020 = data.rename(columns={'Full Name (Data.Home Team)':'Home Team', 'Full Name (Data.Visitor Team)':'Visitor Team'})
nba2020.to_csv('nba2020.csv')

In [8]:
nba2020['Point Difference'] = nba2020['Home Team Score']-nba2020['Visitor Team Score']

In [9]:
nba2020['Home Win'] = np.where(nba2020['Point Difference'] > 0, 1, 0)
nba2020['Home Loss'] = np.where(nba2020['Point Difference'] < 0, 1, 0)
nba2020.drop(columns=['home_win', 'home_loss'])

KeyError: "['home_win' 'home_loss'] not found in axis"

In [10]:
df_visitor = pd.get_dummies(nba2020['Visitor Team'], dtype=np.int64)
df_home = pd.get_dummies(nba2020['Home Team'], dtype=np.int64)

In [11]:
df_model = df_home.sub(df_visitor) 
df_model['Point Difference'] = nba2020['Point Difference']

In [ ]:
df_model.head()

In [3]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import Ridge

In [4]:
df_train = df_model 

lr = Ridge(alpha=0.001) 
X = df_train.drop(['Point Difference'], axis=1)
y = df_train['Point Difference']

lr.fit(X, y)

NameError: name 'df_model' is not defined

In [38]:
df_ratings = pd.DataFrame(data={'team': X.columns, 'rating': lr.coef_})
df_ratings

                      team     rating
0            Atlanta Hawks   2.205903
1           Boston Celtics   1.317621
2            Brooklyn Nets   5.331597
3        Charlotte Hornets  -2.254194
4            Chicago Bulls  -0.934875
5      Cleveland Cavaliers  -8.241444
6         Dallas Mavericks   2.480117
7           Denver Nuggets   4.790087
8          Detroit Pistons  -4.374829
9    Golden State Warriors   1.019226
10         Houston Rockets  -7.505012
11          Indiana Pacers  -0.170850
12             LA Clippers   5.789548
13      Los Angeles Lakers   3.029545
14       Memphis Grizzlies   1.335345
15              Miami Heat  -0.803154
16         Milwaukee Bucks   5.666647
17  Minnesota Timberwolves  -5.251709
18    New Orleans Pelicans  -0.145111
19         New York Knicks   2.070932
20   Oklahoma City Thunder -10.131644
21           Orlando Magic  -9.014767
22      Philadelphia 76ers   5.404578
23            Phoenix Suns   5.400428
24  Portland Trail Blazers   1.826267
25        Sacramento Kings  -3.705063
26       San Antonio Spurs  -1.586580
27         Toronto Raptors  -0.534880
28               Utah Jazz   8.771121
29      Washington Wizards  -1.784849

In [40]:
df_ratings.to_csv('team_ratings.csv')

In [42]:
nba2020=nba2020.drop(columns=['home_win', 'home_loss'])
nba2020

,Date,Home Team,Visitor Team,Home Team Score,Visitor Team Score,Point Difference,Home Win,Home Loss
0,2020-12-22T00:00:00.000Z,Brooklyn Nets,Golden State Warriors,125,99,26,1,0
1,2020-12-22T00:00:00.000Z,Los Angeles Lakers,LA Clippers,109,116,-7,0,1
2,2020-12-25T00:00:00.000Z,Miami Heat,New Orleans Pelicans,111,98,13,1,0
3,2020-12-26T00:00:00.000Z,Washington Wizards,Orlando Magic,120,130,-10,0,1
4,2020-12-23T00:00:00.000Z,Cleveland Cavaliers,Charlotte Hornets,121,114,7,1,0
...,...,...,...,...,...,...,...,...
1107,2021-03-25T00:00:00.000Z,Sacramento Kings,Golden State Warriors,141,119,22,1,0
1108,2021-04-09T00:00:00.000Z,Milwaukee Bucks,Charlotte Hornets,119,127,-8,0,1
1109,2021-03-26T00:00:00.000Z,Detroit Pistons,Brooklyn Nets,111,113,-2,0,1
1110,2021-03-27T00:00:00.000Z,Milwaukee Bucks,New York Knicks,96,102,-6,0,1
1111,2021-03-28T00:00:00.000Z,Charlotte Hornets,Phoenix Suns,97,101,-4,0,1

In [43]:
nba2020.to_csv('full_2020_season.csv')